// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tobkmqcbbxulvezhdzzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvYmttcWNiYnh1bHZlemhkenpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDQzMzAsImV4cCI6MjA3MDc4MDMzMH0.l458DTFc2bsYU5d-ghezdyuphbTJP7i4GFNBP0CFJY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});